// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eiedsylaocoqegycnglu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpZWRzeWxhb2NvcWVneWNuZ2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjY1MDAsImV4cCI6MjA2MjcwMjUwMH0.5vZ47w8CcMYX5IePR52K3JrwOADUR_a7L-p6UdQKtHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);